// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"new-world-robot/internal/conf"
	"new-world-robot/internal/server"
	"new-world-robot/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	managerService := service.NewManagerService(bootstrap)
	managerServer := server.NewManagerServer(managerService, bootstrap)
	timerServer := server.NewTimerServer(managerService, bootstrap)
	app := newApp(logger, managerServer, timerServer)
	return app, func() {
	}, nil
}
